projects:
  My AppSync App:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: fepxwp7wvfeyzcf6dqykqhkamm
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        region: us-east-2
      endpoints:
        prod: >-
          https://ektm4sn6rveg5pmpwdonzmo7wi.appsync-api.us-east-2.amazonaws.com/graphql
